/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "arith.h"

bool_t
xdr_sum_args(XDR *xdrs, sum_args *objp)
{
	register int32_t *buf;

	if (!xdr_int(xdrs, &objp->arg1))
		return FALSE;
	if (!xdr_int(xdrs, &objp->arg2))
		return FALSE;
	return TRUE;
}
