/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ARITH_H_RPCGEN
#define _ARITH_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct sum_args {
	int arg1;
	int arg2;
};
typedef struct sum_args sum_args;

#define PROG_ARITH 0x20000000
#define UNO 1

#if defined(__STDC__) || defined(__cplusplus)
#define PROC_SUM 1
extern  int * proc_sum_1(sum_args *, CLIENT *);
extern  int * proc_sum_1_svc(sum_args *, struct svc_req *);
extern int prog_arith_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PROC_SUM 1
extern  int * proc_sum_1();
extern  int * proc_sum_1_svc();
extern int prog_arith_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_sum_args (XDR *, sum_args*);

#else /* K&R C */
extern bool_t xdr_sum_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ARITH_H_RPCGEN */
