/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "test.h"


bool_t xdr_mydata(XDR *xdrs, MyData *data)
{
	return xdr_int(xdrs, &data->id) &&
		   xdr_wrapstring(xdrs, &(data->name)) &&
		   xdr_float(xdrs, &data->value);
}